--
-- PostgreSQL database dump
--


-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 18.1


--
-- Name: board_columns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_columns (
    id bigint NOT NULL,
    key character varying(50) NOT NULL,
    "position" integer NOT NULL,
    title character varying(100) NOT NULL,
    board_id bigint NOT NULL
);


--
-- Name: board_columns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_columns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_columns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: boards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boards (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL
);


--
-- Name: boards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.boards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_member_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_member_hours (
    hours integer NOT NULL,
    group_member_id integer NOT NULL,
    week_id integer NOT NULL
);


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_members (
    group_member_id integer NOT NULL,
    group_member_name character varying(255) NOT NULL
);


--
-- Name: group_members_group_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_members ALTER COLUMN group_member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_group_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_dates (
    id bigint NOT NULL,
    description character varying(150),
    "time" timestamp(6) without time zone NOT NULL
);


--
-- Name: meeting_dates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_dates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_dates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(200),
    "position" integer NOT NULL,
    title character varying(255) NOT NULL,
    column_id bigint NOT NULL
);


--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: weeks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weeks (
    id integer NOT NULL,
    week_number integer NOT NULL
);


--
-- Name: weeks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.weeks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weeks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: board_columns board_columns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_columns
    ADD CONSTRAINT board_columns_pkey PRIMARY KEY (id);


--
-- Name: boards boards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_pkey PRIMARY KEY (id);


--
-- Name: group_member_hours group_member_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_member_hours
    ADD CONSTRAINT group_member_hours_pkey PRIMARY KEY (group_member_id, week_id);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (group_member_id);


--
-- Name: meeting_dates meeting_dates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_dates
    ADD CONSTRAINT meeting_dates_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: weeks uk4laoyjai2bvkhhysygkg2wfb1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weeks
    ADD CONSTRAINT uk4laoyjai2bvkhhysygkg2wfb1 UNIQUE (week_number);


--
-- Name: group_members uk6864gqooqojlf1luqaykem8va; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT uk6864gqooqojlf1luqaykem8va UNIQUE (group_member_name);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: board_columns uk7fjhc7ixjfrv5ijk2iaj9sqnk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_columns
    ADD CONSTRAINT uk7fjhc7ixjfrv5ijk2iaj9sqnk UNIQUE (key);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: weeks weeks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weeks
    ADD CONSTRAINT weeks_pkey PRIMARY KEY (id);


--
-- Name: group_member_hours fk1qwk3bxijghkejr6obd3m6gqs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_member_hours
    ADD CONSTRAINT fk1qwk3bxijghkejr6obd3m6gqs FOREIGN KEY (week_id) REFERENCES public.weeks(id);


--
-- Name: group_member_hours fk93fnlt44njehrilq8cv60fc1o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_member_hours
    ADD CONSTRAINT fk93fnlt44njehrilq8cv60fc1o FOREIGN KEY (group_member_id) REFERENCES public.group_members(group_member_id);


--
-- Name: tasks fknqexak2pk53qnyxp8rp9nkmkh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fknqexak2pk53qnyxp8rp9nkmkh FOREIGN KEY (column_id) REFERENCES public.board_columns(id);


--
-- Name: board_columns fko1sor7ye3cajl7ut1kc3dhg10; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_columns
    ADD CONSTRAINT fko1sor7ye3cajl7ut1kc3dhg10 FOREIGN KEY (board_id) REFERENCES public.boards(id);


--
-- PostgreSQL database dump complete
--


